
version: '3.2'
services:
  dockerized:
    # to enable caching, uncomment and set this:
    # image: <IMAGE_IDENTIFIER>
    build:
      context: .
      dockerfile: Dockerfile.dockerized
      # to enable caching, uncomment and set this:
      # cache_from:
      #   - <IMAGE_IDENTIFIER>
    environment:
      - USER
      - CARGO_HOME=/root/cargo-cache
    entrypoint:
      - sh
      - '-c'
    volumes:
      - cargo-cache:/root/cargo-cache

volumes:
  cargo-cache: {}
