[package]
name = "app"
version = "0.1.0"
authors = ["benzaita"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.8"
rodio = "0.10"
dialoguer = "0.7"
serde_json = "1.0"